### Numpy

##### What is Numpy?

Multi-Dimensional array library

In [2]:
import numpy as np
print(len(dir(np))) # all the attributes and methods in numpy

622


### Basics

In [27]:
a = np.array([1, 2, 3],dtype ='int16')  #one dimensional
print(a)

[1 2 3]


In [17]:
b = np.array([[1, 2, 3], [2,5,6]]) # two dimesional
print(b)

[[1 2 3]
 [2 5 6]]


In [20]:
# get the dimension of an array
print(a.ndim)
b.ndim

1


2

In [23]:
# Get the shape of an array
print(a.shape)
b.shape

(3,)


(2, 3)

In [28]:
# get the type
a.dtype

dtype('int16')

In [31]:
# Get size
print(a.itemsize)
b.itemsize

2


4

In [38]:
#Get total size
noofbytes = a.size *  a.itemsize
print(noofbytes)
b.nbytes

6


24

### Accessing/Changing specific element, rows, columns, etc

In [66]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [55]:
# Get a specific element [r, c]
a[1, 5]

13

In [53]:
#Get specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [54]:
#Get specific column
a[:, 3]

array([ 4, 11])

In [56]:
# [startindex:endindex:stepsize]
a[0, 1:6:3]

array([2, 5])

In [67]:
# if you want to change any value in array
a[0,4] = 34
print(a)

[[ 1  2  3  4 34  6  7]
 [ 8  9 10 11 12 13 14]]


In [69]:
a[:, 3] = [1,2]
print(a)

[[ 1  2  3  1 34  6  7]
 [ 8  9 10  2 12 13 14]]


### 3-Dimensional

In [73]:
a = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [74]:
# Specific element (0 is for first set)
a[0,1,1]

4

In [75]:
a[:,0,:]

array([[1, 2],
       [5, 6]])

In [78]:
#replace
a[:,0,:] = [[3,3],[7,7]]
a

array([[[3, 3],
        [3, 4]],

       [[7, 7],
        [7, 8]]])

### Initializing different types of arrays

In [82]:
# All zeros metrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [85]:
# All 1s matrix
np.ones((4,2,2,2))
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [91]:
# Any other numbers
np.full((2,2),8,dtype='float16')

array([[8., 8.],
       [8., 8.]], dtype=float16)

In [95]:
#Any other number (full_like)
np.full_like(a.shape,5)

array([5, 5, 5])

In [97]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.89168516, 0.05182187],
       [0.05924014, 0.44129788],
       [0.83182315, 0.9963857 ],
       [0.8642464 , 0.33973789]])

In [98]:
np.random.random_sample(a.shape)

array([[[0.50372627, 0.9208766 ],
        [0.73583016, 0.80516356]],

       [[0.21025461, 0.59108414],
        [0.78617255, 0.53365196]]])

In [107]:
#Random integer value
np.random.randint(2,6,size=(3,3))

array([[3, 4, 3],
       [2, 4, 2],
       [2, 3, 2]])

In [108]:
#identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [53]:
#repeat an array
arr = np.array([[1,2,3]])
r = np.repeat(arr,3,axis=0)
print(r)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [125]:
a = np.ones((5,5))
print(a)

b = np.zeros((3,3))
b[1,1] = 9
print(b)

a[1:4,1:4] = b
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Becarefull when copying array

In [131]:
a = np.array([1,2,3]) # we didnt mention numpy to copy the array
b = a
b[0]=100
print(a)

[100   2   3]


In [133]:
a = np.array([1,2,3]) 
b = a.copy()
b[0]=100
print(a)

[1 2 3]


# Mathematics

In [134]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [135]:
a+2

array([3, 4, 5])

In [136]:
a-2

array([-1,  0,  1])

In [137]:
a*2

array([2, 4, 6])

In [138]:
a/2

array([0.5, 1. , 1.5])

In [139]:
a%2

array([1, 0, 1], dtype=int32)

In [141]:
b = np.array([1,0,1])
a+b

array([2, 2, 4])

In [143]:
# take sign of all the values
np.sin(a)
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 ])

# Linear Algebra

In [147]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [148]:
a = np.identity(3)
np.linalg.det(a)

1.0

In [151]:
a = np.array([[2,-1,3,0],[-3,1,0,4],[-2,1,4,1],[-1,3,0,-2]])
np.linalg.det(a)

-102.00000000000004

#### Statistics

In [3]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
np.min(stats)

1

In [6]:
np.max(stats)

6

In [8]:
np.max(stats, axis=0)
np.max(stats, axis=1)

array([3, 6])

In [9]:
np.sum(stats)

21

In [10]:
np.sum(stats,axis=0)

array([5, 7, 9])

In [11]:
np.sum(stats, axis=1)

array([ 6, 15])

#### Reorganizing Arrays

In [12]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before.shape)

(2, 4)


In [20]:
after = before.reshape(2,2,2)
print(after)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [21]:
#Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [26]:
#Horizontal Stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h2,h1))

array([[0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.]])

### Miscelleneous

#### Load data from File

In [35]:
filedata = np.genfromtxt('data.txt',delimiter=',')
filedata = filedata.astype('int32')
filedata

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [11, 12, 13, 14, 15, 16, 17, 18],
       [21, 22, 23, 24, 25, 26, 27, 28]])

### Boolean Masking and Advanced indexing

In [37]:
filedata > 20

array([[False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [ True,  True,  True,  True,  True,  True,  True,  True]])

In [38]:
filedata[filedata > 10]

array([11, 12, 13, 14, 15, 16, 17, 18, 21, 22, 23, 24, 25, 26, 27, 28])

In [48]:
print(filedata)
np.any(filedata > 10, axis = 0)

[[ 1  2  3  4  5  6  7  8]
 [11 12 13 14 15 16 17 18]
 [21 22 23 24 25 26 27 28]]


In [51]:
(((filedata > 10) & (filedata < 25)))

array([[False, False, False, False, False, False, False, False],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False, False, False]])